name: Pester
on:
  push:
    branches: [ master ]
jobs:
  test-pwsh:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Pester tests
      shell: pwsh
      run: |
        Set-PSRepository psgallery -InstallationPolicy trusted
        Install-Module -Name Pester -RequiredVersion 5.2.1 -Confirm:$false -Force
        Invoke-Pester -Path "tests"