Properties {
  # Set this to $true to create a module with a monolithic PSM1
  $PSBPreference.Build.CompileModule = $True
  $PSBPreference.Build.CompileHeader = @'
#Requires -Version 5.1
using namespace System.Management.Automation

# Module initialization
$ErrorActionPreference = 'Stop'
$InformationPreference = 'Continue'

'@
  $PSBPreference.Help.DefaultLocale = 'en-US'
  $PSBPreference.Test.OutputFile = 'out/testResults.xml'
  $PSBPreference.Build.CopyDirectories = @('en-US', 'Schema', 'Templates')
}

Task Default -Depends Test

Task Test -FromModule PowerShellBuild -MinimumVersion '0.6.1'

# Export-LocalizationJson: Convert all Plaster.Resources.psd1 files to JSON for CrowdIn
Task ExportLocalizationJson {
  $importLocalizedDataSplat = @{
    BindingVariable = 'LocalizedData'
    FileName = 'Plaster.Resources.psd1'
    ErrorAction = 'SilentlyContinue'
  }
  # Import the en-US localized data
  Microsoft.PowerShell.Utility\Import-LocalizedData @importLocalizedDataSplat
  # Create the i18n directory if it doesn't exist
  if (-not (Test-Path "i18n")) {
    New-Item -Path "i18n" -ItemType Directory | Out-Null
  }

  # Convert the localized data to JSON and save it
  $jsonContent = $LocalizedData | ConvertTo-Json -Depth 10
  $jsonPath = Join-Path "i18n" "Plaster.Resources.en-US.json"
  Set-Content -Path $jsonPath -Value $jsonContent -Encoding UTF8
}

# Convert all i18n/Plaster.Resources.<locale>.json files to psd1 for runtime
Task GenerateLocalizationPsd1 {
  $jsonFiles = Get-ChildItem -Path "i18n" -Filter "Plaster.Resources.*.json" -File
  foreach ($jsonFile in $jsonFiles) {
    if ($jsonFile.Name -match "^Plaster\.Resources\.([^.]+)\.json$") {
      $locale = $matches[1]
      $psd1Dir = Join-Path "Plaster" $locale
      if (-not (Test-Path $psd1Dir)) { New-Item -Path $psd1Dir -ItemType Directory | Out-Null }
      $psd1Path = Join-Path $psd1Dir "Plaster.Resources.psd1"
      $data = Get-Content $jsonFile.FullName | ConvertFrom-Json
      $stringData = ($data.PSObject.Properties | Sort-Object Name | ForEach-Object {
          "$($_.Name)=$($_.Value)"
        }) -join "`n"
      $psd1Content = @"
#### WARNING: This file is auto-generated from $($jsonFile.Name).
#### Do not edit this file directly. Instead, update the source JSON file in the i18n directory.
# Localized PlasterResources.psd1
# This file was generated from $($jsonFile.Name) using a Psake task.
ConvertFrom-StringData @'
$stringData
'@
"@
      Set-Content $psd1Path $psd1Content -Encoding UTF8
      Write-Host "Imported $jsonFile to $psd1Path"
    }
  }
}
