-- Configure  the number of logs as <%= $PLASTER_PARAM_NUMBERLOGS %> for instance <%= $PLASTER_PARAM_INSTANCENAME %>
-- AutoGenerated on <%= Get-Date %>
USE [master]
GO
EXEC xp_instance_regwrite N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\MSSQLServer', N'NumErrorLogs', REG_DWORD, <%= [int] $PLASTER_PARAM_NUMBERLOGS %>
GO