function <%= $PLASTER_PARAM_ScriptName %> {
    [CmdletBinding()]
    param(
        [Parameter(Position = 0)]
        [string]$Name = 'World'
    )
    "<%= $PLASTER_PARAM_Greeting %>, $Name!"
}

# Generated by Plaster (JSON manifest) on <%= (Get-Date).ToString('yyyy-MM-dd') %>
