name: Publish Module
on:
  # Only on workflow dispatch, so that we can control when to publish.
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: ⚡ ModuleFast with Specification
        uses: JustinGrote/ModuleFast-action@v0.0.1
        with:
          specification: |
            BuildHelpers
            PowerShellBuild
            psake
            PSScriptAnalyzer
            platyPS
      - name: Build and publish
        env:
          PSGALLERY_API_KEY: ${{ secrets.GALLERY_KEY }}
        shell: pwsh
        run: |
          ./build.ps1 -Task Publish -Bootstrap
